name: splitting
services:
  challenge:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "11119:11119"
    environment:
      FLAG: "IERAE{7de6b745404269a0d7b40955047921c6860e4438c73eb095090e75c8fb00cb51}"
    deploy:
      resources:
        reservations:
          memory: 256M
