services:
  app:
    build: ./app
    init: true
    ports:
      - 9000
    environment:
      - APP_ENV=production
      - FLAG=IERAE{REDACTED}

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - app
